# .github/actions/publish-pwsh-module/action.yml
name: "Publish PowerShell Module"
description: "Reusable action to build, tag, validate, and publish a PowerShell module to the PowerShell Gallery."
author: "itmvha"

inputs:
  psd1Path:
    description: "Path to the PSD1 manifest file."
    required: true
  psm1Path:
    description: "Path to the PSM1 module file."
    required: true
  companyName:
    description: "The name of the company required by nuget"
    required: true
  apiKey:
    description: "NuGet API key for publishing to the PowerShell Gallery."
    required: true
    secret: true
  rootModule:
    description: "the name of the module."
    required: true
  description:
    description: "the description for the module."
    required: true

runs:
  using: "composite"
  steps:


    # Step 3: Get commit message
    - name: Get commit message
      id: commitMessage
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      shell: bash

    # Step 4: Create module manifest
    - name: Create module manifest
      run: |
        New-ModuleManifest -Path "${{ inputs.psd1Path }}" `
        -RootModule "${{ inputs.rootModule }}" `
        -FunctionsToExport '*' `
        -Author "itmvha" -ModuleVersion "${{ steps.gitversion.outputs.semVer }}" `
        -Description "${{ inputs.description }}" `
        -CompanyName "${{ inputs.companyName }}" `
        -ReleaseNotes "$env:message"
      shell: powershell

    # Step 5: Test module manifest
    - name: Test module manifest
      run: |
        Test-ModuleManifest -Path "${{ inputs.psd1Path }}"
      shell: powershell

    # Step 6: Publish PowerShell module
    - name: Publish to PowerShell Gallery
      run: |
        Publish-Module -Path "${{ inputs.psm1Path }}" -NuGetApiKey "${{ inputs.apiKey }}"
      shell: powershell
