name: Package PowerShell Script

on:
  push:
    paths:
      - 'pwsh/**'  # Trigger the workflow only when changes are made in the pwsh folder
  pull_request:
    paths:
      - 'pwsh/**'  # Trigger the workflow only for PRs involving changes in the pwsh folder

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install the PS2EXE module
      - name: Install PS2EXE module
        run: |
          Install-Module -Name PS2EXE -Scope CurrentUser -Force
        shell: pwsh

      # Step 3: Create output directory for the exe file
      - name: Create output directory
        run: |
          mkdir $env:GITHUB_WORKSPACE\output
        shell: pwsh

      # Step 4: Copy the pwsh directory to the output directory
      - name: Copy scripts to output directory
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE\pwsh\*" -Destination "$env:GITHUB_WORKSPACE\output" -Recurse
        shell: pwsh

      # Step 5: Package the PowerShell script into an executable
      - name: Package PowerShell script into EXE
        run: |
          Invoke-PS2EXE -InputFile "$env:GITHUB_WORKSPACE\output\main.ps1" -OutputFile "$env:GITHUB_WORKSPACE\output\PDS.exe"
        shell: pwsh

      # Step 6: Upload the executable as an artifact
      - name: Upload packaged EXE
        uses: actions/upload-artifact@v3
        with:
          name: packaged-script
          path: ${{ github.workspace }}/output/PDS.exe
