## reference
## https://stackoverflow.com/questions/75008756/running-ps2exe-in-github-actions
name: Package PowerShell Script

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pwsh/scripts/**'
      - '!**/*.md'
      - '!.gitignore'
  pull_request:
    branches:
      - main
    paths:
      - 'pwsh/scripts/**'
      - '!**/*.md'
      - '!.gitignore'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Package PowerShell Script
        uses: michielvha/package-pwsh-script-action@v1
        with:
          name: 'PDS'
          script-path: 'pwsh/scripts/main.ps1'
          config-file: 'gitversion.yml'
