# .github/workflows/publish-module.yml
name: Publish PowerShell Module

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'pwsh/module/**'
  pull_request:
    branches:
      - main
    paths:
      - 'pwsh/module/**'

jobs:
  publish:
    runs-on: windows-latest

    steps:
#    # Step 1: Checkout code
#    - name: Checkout code
#      uses: actions/checkout@v4
#      with:
#        fetch-depth: 0
#
#    # Step 2: Debug Step - Verify Directory Structure and Files
#    - name: Debug - List Files and Verify Paths
#      run: |
#        Write-Host "Workspace Directory Structure:"
#        Get-ChildItem -Path "${{ github.workspace }}" -Recurse
#        Write-Host "Checking for PSD1 and PSM1 Files..."
#        if (Test-Path "${{ github.workspace }}\pwsh\module\PDS.psd1") {
#          Write-Host "Found PDS.psd1 file."
#        } else {
#          Write-Error "PDS.psd1 file not found at expected path."
#        }
#        if (Test-Path "${{ github.workspace }}\pwsh\module\PDS.psm1") {
#          Write-Host "Found PDS.psm1 file."
#        } else {
#          Write-Error "PDS.psm1 file not found at expected path."
#        }
#      shell: powershell

    # Step 2: Publish PowerShell Module
    - name: Publish PowerShell Module
      uses: MKTHEPLUGG/publish-pwsh-module-action@v2
      with:
        psd1Path: "${{ github.workspace }}\\pwsh\\module\\PDS.psd1"   # Updated with consistent backslashes
        psm1Path: "${{ github.workspace }}\\pwsh\\module\\PDS.psm1"   # Updated with consistent backslashes
        apiKey: ${{ secrets.API_KEY }}
        description: "Personal Deploy Script"
        rootModule: "PDS"
        companyName: "meti.pro"
