name: Publish PowerShell Module
permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'pwsh/module/**'
      - '!**/*.md'
      - '!.gitignore'
  pull_request:
    branches:
      - main
    paths:
      - 'pwsh/module/**'
      - '!**/*.md'
      - '!.gitignore'
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish PowerShell Module
        uses: michielvha/publish-pwsh-module-action@v2
        with:
          psd1Path: "${{ github.workspace }}\\pwsh\\module\\PDS.psd1" # Updated with consistent backslashes
          psm1Path: "${{ github.workspace }}\\pwsh\\module\\PDS.psm1" # Updated with consistent backslashes
          apiKey: ${{ secrets.API_KEY }}
          description: "Personal Deploy Script"
          rootModule: "PDS"
          companyName: "itmvha"
